name: OpTalk
main: be.infogroep.optalk.optalk
version: 0.5.3
author: spartam

commands:
  o:
    description: Send a message to all operators
    usage: /o <message>
    permission: OpTalk.o
    permission-message: How do you even know I exist?
  
permissions:
  OpTalk.item:
    default: true